configured_endpoints: 24
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/okii/front-of-house-api-34fa02bcef3715dcf2fb4ffd2ee7df229d67c94b2c529e3dcf7c7ff2c3be0581.yml
openapi_spec_hash: 297f6203be12b0b11c77b67ae452f15e
config_hash: c94454b6a10fde569fcb8c8acf49cfcc
